name: Parser

on:
  push:
    branches:
      - main

jobs:
  parse-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run parser
        run: |
          mkdir -p output
          python parser.py \
            --log nginx.log \
            --output output/result.csv

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-csv
          path: output/result.csv
